// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
	GetDefinitionsData,
	GetDefinitionsErrors,
	GetDefinitionsResponses,
	GetDirectivesData,
	GetDirectivesErrors,
	GetDirectivesResponses,
	PostDefinitionsSaveData,
	PostDefinitionsSaveErrors,
	PostDefinitionsSaveResponses,
} from './types.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class Definitions {
	public static getDefinitions<ThrowOnError extends boolean = true>(
		options?: Options<GetDefinitionsData, ThrowOnError>,
	): RequestResult<GetDefinitionsResponses, GetDefinitionsErrors, ThrowOnError> {
		return (options?.client ?? client).get<GetDefinitionsResponses, GetDefinitionsErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Definitions',
			...options,
		});
	}

	public static postDefinitionsSave<ThrowOnError extends boolean = true>(
		options: Options<PostDefinitionsSaveData, ThrowOnError>,
	): RequestResult<PostDefinitionsSaveResponses, PostDefinitionsSaveErrors, ThrowOnError> {
		return (options.client ?? client).post<PostDefinitionsSaveResponses, PostDefinitionsSaveErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Definitions/save',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		});
	}
}

export class Directives {
	public static getDirectives<ThrowOnError extends boolean = true>(
		options?: Options<GetDirectivesData, ThrowOnError>,
	): RequestResult<GetDirectivesResponses, GetDirectivesErrors, ThrowOnError> {
		return (options?.client ?? client).get<GetDirectivesResponses, GetDirectivesErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Directives',
			...options,
		});
	}
}
