// This file is auto-generated by @hey-api/openapi-ts

export type CspDefinition = {
    id: string;
    enabled: boolean;
    reportOnly: boolean;
    isBackOffice: boolean;
    reportingDirective?: string | null;
    reportUri?: string | null;
    sources: Array<CspDefinitionSource>;
};

export type CspDefinitionSource = {
    definitionId: string;
    source: string;
    directives: Array<string>;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type GetDefinitionsData = {
    body?: never;
    path?: never;
    query?: {
        isBackOffice?: boolean;
    };
    url: '/Definitions';
};

export type GetDefinitionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetDefinitionsResponses = {
    /**
     * OK
     */
    200: CspDefinition;
};

export type GetDefinitionsResponse = GetDefinitionsResponses[keyof GetDefinitionsResponses];

export type PostDefinitionsSaveData = {
    body?: CspDefinition;
    path?: never;
    query?: never;
    url: '/Definitions/save';
};

export type PostDefinitionsSaveErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostDefinitionsSaveResponses = {
    /**
     * OK
     */
    200: CspDefinition;
};

export type PostDefinitionsSaveResponse = PostDefinitionsSaveResponses[keyof PostDefinitionsSaveResponses];

export type GetDirectivesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Directives';
};

export type GetDirectivesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetDirectivesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetDirectivesResponse = GetDirectivesResponses[keyof GetDirectivesResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44370' | (string & {});
};