// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: 'https://localhost:44370/' | (string & {});
};

export type CspApiDefinition = {
	id: string;
	enabled: boolean;
	reportOnly: boolean;
	isBackOffice: boolean;
	reportingDirective?: null | string;
	reportUri?: null | string;
	upgradeInsecureRequests: boolean;
	sources: Array<CspApiDefinitionSource>;
};

export type CspApiDefinitionSource = {
	definitionId: string;
	source: string;
	directives: Array<string>;
};

export type ProblemDetails = {
	type?: null | string;
	title?: null | string;
	status?: null | number | string;
	detail?: null | string;
	instance?: null | string;
};

export type GetDefinitionsData = {
	body?: never;
	path?: never;
	query?: {
		isBackOffice?: boolean;
	};
	url: '/umbraco/csp/api/v1/Definitions';
};

export type GetDefinitionsErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type GetDefinitionsResponses = {
	/**
	 * OK
	 */
	200: CspApiDefinition;
};

export type GetDefinitionsResponse = GetDefinitionsResponses[keyof GetDefinitionsResponses];

export type PostDefinitionsSaveData = {
	body: CspApiDefinition;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/Definitions/save';
};

export type PostDefinitionsSaveErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type PostDefinitionsSaveError = PostDefinitionsSaveErrors[keyof PostDefinitionsSaveErrors];

export type PostDefinitionsSaveResponses = {
	/**
	 * OK
	 */
	200: CspApiDefinition;
};

export type PostDefinitionsSaveResponse = PostDefinitionsSaveResponses[keyof PostDefinitionsSaveResponses];

export type GetDirectivesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/Directives';
};

export type GetDirectivesErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type GetDirectivesResponses = {
	/**
	 * OK
	 */
	200: Array<string>;
};

export type GetDirectivesResponse = GetDirectivesResponses[keyof GetDirectivesResponses];
