// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type {
	GetUmbracoManagementApiV1CspManageDirectivesResponse,
	GetUmbracoManagementApiV1CspManageGetByIsBackOfficeData,
	GetUmbracoManagementApiV1CspManageGetByIsBackOfficeResponse,
	PostUmbracoManagementApiV1CspManageSaveData,
	PostUmbracoManagementApiV1CspManageSaveResponse,
} from './types.gen';

/**
 * @returns string OK
 * @throws ApiError
 */
export const getUmbracoManagementApiV1CspManageDirectives =
	(): CancelablePromise<GetUmbracoManagementApiV1CspManageDirectivesResponse> => {
		return __request(OpenAPI, {
			method: 'GET',
			url: '/umbraco/management/api/v1/csp/manage/directives',
			errors: {
				401: 'The resource is protected and requires an authentication token',
			},
		});
	};

/**
 * @param data The data for the request.
 * @param data.isBackOffice
 * @returns unknown OK
 * @throws ApiError
 */
export const getUmbracoManagementApiV1CspManageGetByIsBackOffice = (
	data: GetUmbracoManagementApiV1CspManageGetByIsBackOfficeData,
): CancelablePromise<GetUmbracoManagementApiV1CspManageGetByIsBackOfficeResponse> => {
	return __request(OpenAPI, {
		method: 'GET',
		url: '/umbraco/management/api/v1/csp/manage/get/{isBackOffice}',
		path: {
			isBackOffice: data.isBackOffice,
		},
		errors: {
			401: 'The resource is protected and requires an authentication token',
		},
	});
};

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown OK
 * @throws ApiError
 */
export const postUmbracoManagementApiV1CspManageSave = (
	data: PostUmbracoManagementApiV1CspManageSaveData = {},
): CancelablePromise<PostUmbracoManagementApiV1CspManageSaveResponse> => {
	return __request(OpenAPI, {
		method: 'POST',
		url: '/umbraco/management/api/v1/csp/manage/save',
		body: data.requestBody,
		mediaType: 'application/json',
		errors: {
			401: 'The resource is protected and requires an authentication token',
		},
	});
};
