// This file is auto-generated by @hey-api/openapi-ts

export type CspDefinition = {
	id: string;
	enabled: boolean;
	reportOnly: boolean;
	isBackOffice: boolean;
	reportingDirective?: string | null;
	reportUri?: string | null;
	sources: Array<CspDefinitionSource>;
};

export type CspDefinitionSource = {
	definitionId: string;
	source: string;
	directives: Array<string>;
};

export enum EventMessageTypeModel {
	DEFAULT = 'Default',
	INFO = 'Info',
	ERROR = 'Error',
	SUCCESS = 'Success',
	WARNING = 'Warning',
}

export type NotificationHeaderModel = {
	message: string;
	category: string;
	type: EventMessageTypeModel;
};

export type GetUmbracoManagementApiV1CspManageDirectivesResponse = Array<string>;

export type GetUmbracoManagementApiV1CspManageGetByIsBackOfficeData = {
	isBackOffice: boolean;
};

export type GetUmbracoManagementApiV1CspManageGetByIsBackOfficeResponse = CspDefinition;

export type PostUmbracoManagementApiV1CspManageSaveData = {
	requestBody?: CspDefinition;
};

export type PostUmbracoManagementApiV1CspManageSaveResponse = CspDefinition;

export type $OpenApiTs = {
	'/umbraco/management/api/v1/csp/manage/directives': {
		get: {
			res: {
				/**
				 * OK
				 */
				200: Array<string>;
				/**
				 * The resource is protected and requires an authentication token
				 */
				401: unknown;
			};
		};
	};
	'/umbraco/management/api/v1/csp/manage/get/{isBackOffice}': {
		get: {
			req: GetUmbracoManagementApiV1CspManageGetByIsBackOfficeData;
			res: {
				/**
				 * OK
				 */
				200: CspDefinition;
				/**
				 * The resource is protected and requires an authentication token
				 */
				401: unknown;
			};
		};
	};
	'/umbraco/management/api/v1/csp/manage/save': {
		post: {
			req: PostUmbracoManagementApiV1CspManageSaveData;
			res: {
				/**
				 * OK
				 */
				200: CspDefinition;
				/**
				 * The resource is protected and requires an authentication token
				 */
				401: unknown;
			};
		};
	};
};
