name: "Bug report"
description: "File a bug report to help improve this package."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue as thoroughly as possible.
  - type: dropdown
    id: package
    attributes:
      label: "Which package is this bug related to?"
      options:
        - Umbraco.Community.CSPManager
        - Umbraco.Community.CSPManager.uSync
        - Umbraco.Community.CSPManager.uSync.Complete
        - Not sure
    validations:
      required: true
  - type: input
    id: packageVersion
    attributes:
      label: "Which package version are you using?"
      description: "Leave blank if you're not sure: the latest version will be assumed."
      placeholder: "e.g. 3.1.0"
    validations:
      required: false
  - type: input
    id: umbracoVersion
    attributes:
      label: "Which Umbraco version are you using?"
      description: "Use the help icon in the Umbraco backoffice to find the exact version."
      placeholder: "e.g. 17.0.0"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: "Bug summary"
      description: "Describe the bug. Try to state the actual problem, not just what you think the solution might be."
      placeholder: |
        Try to pinpoint it as much as possible.

        You can format code and logs nicely with triple backticks (```).
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to reproduce"
      description: "How can we reproduce the problem on a clean Umbraco install with this package?"
      placeholder: |
        1. Install package...
        2. Navigate to...
        3. Click on...
        4. See error...

        Please include any links, screenshots, or stack traces.
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: "Expected result / actual result"
      description: "What did you expect to happen, and what actually happened?"
      placeholder: |
        Expected: ...
        Actual: ...
    validations:
      required: true
