name: 'Test Report'
on:
  workflow_run:
    workflows: [Build]                     # runs after Build workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: .NET Tests                  # Name of the check run which will be created
        path: "**/test-results.trx"                   # Path to test results (inside artifact .zip)
        reporter: dotnet-trx